net: macb: Remove redundant ptp clock selection
Source: Xilinx
MR: 96034
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v4.14
ChangeID: 339b16e52ab0db66feea57b28753bb90d80798ca
Description:

PTP_1588_CLOCK is already implied when MACB_USE_HWSTAMP is selected.
Remove the unconditional selection under macb config.
Also using the imply instead of select avoid errors on configurations
such as:

	make ARCH=i386

All errors (new ones prefixed by >>):

   drivers/ptp/ptp_clock.o: In function `ptp_clock_register':
>> drivers/ptp/ptp_clock.c:274: undefined reference to `posix_clock_register'
   drivers/ptp/ptp_clock.o: In function `ptp_clock_unregister':
>> drivers/ptp/ptp_clock.c:320: undefined reference to `posix_clock_unregister'

Signed-off-by: Harini Katakam <harini.katakam@xilinx.com>
Acked-by: Radhey Shyam Pandey <radheys@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>