serial: uartlite: Fix compilation issue on !OF platforms
Source: Xilinx
MR: 96034
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v4.14
ChangeID: 5f860c486f994ce0d449e1b715e755d6153f0ffb
Description:

There is missing ulite_of_match on !OF platforms.
Use of_match_ptr() to fix it.

Warning log:
drivers/tty/serial/uartlite.c: In function ‘ulite_get_id’:
drivers/tty/serial/uartlite.c:774:33: error: ‘ulite_of_match’ undeclared
(first use in this function)
   ret = of_alias_get_alias_list(ulite_of_match, "serial",
                                 ^
drivers/tty/serial/uartlite.c:774:33: note: each undeclared identifier
is reported only once for each function it appears in

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>