soc: xilinx: xlnx_vcu: Depends on HAS_IOMEM for xlnx_vcu
Source: Xilinx
MR: 96034
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v4.14
ChangeID: 5811f05249170f5c03ae706e068c1e03d67b535f
Description:

xlnx_vcu driver uses devm_ioremap_nocache, which is included
only when HAS_IOMEM is enabled.

drivers/soc/xilinx/xlnx_vcu.o: In function `xvcu_probe':
   xlnx_vcu.c:(.text+0x116): undefined reference to `devm_ioremap_nocache'
   xlnx_vcu.c:(.text+0x1ae): undefined reference to `devm_ioremap_nocache'

Signed-off-by: Dhaval Shah <dshah@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>